### ISSUE TITLE
pg_ident.conf should be processed like the pg_hba.conf

### ISSUE THREAD

**Issue by antonov-impulsm** [polymorphm/archlinux-postgresql-upgrade#2]
old-data: ``pg_ident.conf`` -> ``pg_ident.conf.save``
new-data: ``pg_ident.conf`` -> ``pg_ident.conf.original``
upgrade phase: ``pg_ident.conf.save`` -> ``pg_ident.conf``

**Comment by polymorphm** [comment]
solved in e6760dd9c
